/* tslint:disable */
/* eslint-disable */
/**
 * Patient Management API
 * API for managing patient profiles
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PatientContactInfo,
    PatientContactInfoFromJSON,
    PatientContactInfoFromJSONTyped,
    PatientContactInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface PatientInput
 */
export interface PatientInput {
    /**
     * 
     * @type {string}
     * @memberof PatientInput
     */
    fullName: string;
    /**
     * 
     * @type {Date}
     * @memberof PatientInput
     */
    dateOfBirth: Date;
    /**
     * 
     * @type {PatientContactInfo}
     * @memberof PatientInput
     */
    contactInfo: PatientContactInfo;
    /**
     * 
     * @type {string}
     * @memberof PatientInput
     */
    adhdDiagnosis: PatientInputAdhdDiagnosis;
    /**
     * 
     * @type {string}
     * @memberof PatientInput
     */
    additionalNotes?: string | null;
}

/**
* @export
* @enum {string}
*/
export enum PatientInputAdhdDiagnosis {
    Mild = 'Mild',
    Moderate = 'Moderate',
    Severe = 'Severe'
}

export function PatientInputFromJSON(json: any): PatientInput {
    return PatientInputFromJSONTyped(json, false);
}

export function PatientInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatientInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': json['fullName'],
        'dateOfBirth': (new Date(json['dateOfBirth'])),
        'contactInfo': PatientContactInfoFromJSON(json['contactInfo']),
        'adhdDiagnosis': json['adhdDiagnosis'],
        'additionalNotes': !exists(json, 'additionalNotes') ? undefined : json['additionalNotes'],
    };
}

export function PatientInputToJSON(value?: PatientInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fullName': value.fullName,
        'dateOfBirth': (value.dateOfBirth.toISOString().substr(0,10)),
        'contactInfo': PatientContactInfoToJSON(value.contactInfo),
        'adhdDiagnosis': value.adhdDiagnosis,
        'additionalNotes': value.additionalNotes,
    };
}

